spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8888


gateway:
  public-routes:
    - method: POST
      path: /api/v1/orders/**
    - method: GET
      path: /api/v1/products/**
    - method: GET
      path: /api/v1/inventory/**
    - method: GET
      path: /actuator/health
    - method: GET
      path: /actuator/info