apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecommerce
  labels:
    app: product-service
    track: stable
spec:
  replicas: 8
  selector:
    matchLabels:
      app: product-service
      track: stable
  template:
    metadata:
      labels:
        app: product-service
        track: stable
    spec:
      containers:
        - name: product-service
          image: ghcr.io/aymanprocessor/e-commerce-microservice/product-service:latest
          
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: eureka.url
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: datasource.url
          